// Generated by CoffeeScript 1.3.1
(function() {
  var Repositories, collection, helpers, pd, validator;

  helpers = require("./helpers");

  validator = require("./validator");

  collection = require("mongo-col");

  pd = require("pd");

  Repositories = {
    createRepository: function(name, content) {
      var db;
      db = collection(name, process.env["MONGODB_DATABASE"]);
      return pd.extend(Object.create(db), content, {
        ObjectId: require("mongodb").ObjectID,
        baseSave: function(object, callback) {
          var that;
          that = this;
          return validator.validate(name, object, function(errors) {
            var objectToUpdate;
            if (errors) {
              return callback(object, errors);
            } else {
              if (helpers.isNew(object)) {
                object._id = new that.ObjectId();
                db.save(object, function(err) {
                  if (err) {
                    console.log(err);
                    return callback(object, err);
                  }
                });
              } else {
                objectToUpdate = pd.extend({}, object);
                delete objectToUpdate._id;
                db.update({
                  _id: that.ObjectId(object._id)
                }, {
                  $set: objectToUpdate
                }, function(err) {
                  if (err) {
                    console.log(err);
                    return callback(object, err);
                  }
                });
              }
              return callback(object);
            }
          });
        }
      });
    }
  };

  module.exports = Repositories;

}).call(this);
