// Generated by CoffeeScript 1.3.1
(function() {
  var Repository, collection, helpers, pd, validator;

  helpers = require("./helpers");

  validator = require("./validator");

  collection = require("mongo-col");

  pd = require("pd");

  Repository = {
    createRepository: function(name, content) {
      var db;
      db = collection(name, process.env["MONGODB_DATABASE"]);
      return pd.extend(Object.create(db), content, {
        ObjectId: require("mongodb").ObjectID,
        baseSave: function(object, callback) {
          return validator.validate(name, object, function(errors) {
            if (errors) {
              return callback(object, errors);
            } else {
              return db.save(object, function(err) {
                if (err) {
                  console.log(err);
                  return callback(object, err);
                }
              });
            }
          });
        }
      });
    }
  };

  module.exports = Repository;

}).call(this);
