// Generated by CoffeeScript 1.3.1
(function() {
  var Router;

  Router = {
    getAction: function(controller, action) {
      return function(req, res) {
        if (typeof controller.initialize === "function") {
          controller.initialize(req, res);
        }
        return controller[action](req, res);
      };
    }
  };

  module.exports = Router;

}).call(this);
