// Generated by CoffeeScript 1.3.1
(function() {
  var Users, createRepository;

  createRepository = require("../../libs/repositories").createRepository;

  Users = createRepository("users", {
    byUsernameAndPassword: function(username, password, callback) {
      return this.findOne({
        username: username,
        password: password
      }, function(err, user) {
        if (err) {
          console.log(err);
        }
        return callback(user ? user : null);
      });
    }
  });

  module.exports = Users;

}).call(this);
