// Generated by CoffeeScript 1.3.1
(function() {
  var HomeController;

  HomeController = {
    index: function(req, res) {
      return res.render("index", {
        title: "ThinAir"
      });
    }
  };

  module.exports = HomeController;

}).call(this);
