// Generated by CoffeeScript 1.3.1
(function() {
  var ProjectController, helpers;

  helpers = require("../../libs/helpers");

  ProjectController = {
    Projects: null,
    initialize: function(req, res) {
      helpers.checkIfAuthorized(req, res);
      return this.Projects = this.repositories.Projects;
    },
    list: function(req, res) {
      var that;
      that = this;
      return this.Projects.allByDate(function(projects) {
        if (projects) {
          return res.render("projects/list", {
            title: "List of projects",
            projects: projects
          });
        } else {
          that.messages.addMessage(req, "error", "No projects found.");
          return res.redirect("/");
        }
      });
    },
    "new": function(req, res) {
      return res.render("projects/edit", {
        title: "Create a new project"
      });
    },
    editGet: function(req, res) {
      var that;
      that = this;
      return this.Projects.byCode(req.params.project_code, function(project) {
        if (project) {
          return res.render("projects/edit", {
            title: "Editing project: " + project.name,
            project: project
          });
        } else {
          that.messages.addMessage(req, "error", "Unable to find project.");
          return res.redirect("/projects");
        }
      });
    },
    editPost: function(req, res) {
      var that;
      that = this;
      return this.Projects.save(req.body.project, function(project, errors) {
        if (errors) {
          that.validator.flashErrors(req, errors);
        } else {
          that.messages.addMessage(req, "success", "Saved with success.");
        }
        return res.render("projects/edit", {
          title: "Editing project: " + project.name,
          project: project
        });
      });
    },
    "delete": function(req, res) {
      var that;
      that = this;
      return this.Projects["delete"](req.params.project_code, function(err) {
        if (!err) {
          that.messages.addMessage(req, "success", "Project with code \"" + req.params.project_code + "\" has been deleted with success.");
        }
        return res.redirect("/projects");
      });
    }
  };

  module.exports = ProjectController;

}).call(this);
