// Generated by CoffeeScript 1.3.1
(function() {
  var UserController, helpers;

  helpers = require("../../libs/helpers");

  UserController = {
    Users: null,
    initialize: function(req, res) {
      return this.Users = this.repositories.Users;
    },
    login: function(req, res) {
      var password, that, username;
      username = req.body.username;
      password = req.body.password;
      that = this;
      return this.Users.byUsernameAndPassword(username, password, function(user) {
        if (!user) {
          that.messages.addMessage(req, "error", "We are unable to find this user or maybe your password is wrong? Please try again.");
        } else {
          req.session.is_logged = true;
          req.session.username = username;
          that.messages.addMessage(req, "success", "Welcome back " + username + "!");
        }
        return res.redirect("/");
      });
    },
    logout: function(req, res) {
      req.session.is_logged = null;
      req.session.username = null;
      return res.redirect("/");
    }
  };

  module.exports = UserController;

}).call(this);
